version: '3.0'

services:
  tgbot:
    image: fdagsdfgs/tgbot:latest
    container_name: tgbot
    restart: always
    pid: host
    privileged: true
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      TGBOT_TOKEN:
