# 更新dogyun的cookie触发tg机器人后台重启
name: update dogyun
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
          cache: pip

      - name: Generate settings/config.py
        env:
          TGBOT_TOKEN: ${{secrets.TGBOT_TOKEN}}
        run: |
          python config_gen.py $TGBOT_TOKEN

      - name: 更新tgbot
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        continue-on-error: true
        with:
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          pass: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          connect_timeout: 10s
          first_ssh: |
            cd /root/code/tgbot
            git checkout .
            git pull
          scp: |
            './settings/config.py' => /root/code/tgbot/settings
          last_ssh: |
            systemctl restart tgbot
